#!/usr/bin/env ruby

version = ARGV[0]

root_dir = File.expand_path("../", __dir__)

index_src = File.join(root_dir, "README.md")
index_src_content = File.read(index_src)
index_src_content.gsub!(/\(.*\)LICENSE/, "\\1{{ site.baseurl }}\/license.html")

# Build index.html from current README.md
#
index_dest = File.join(root_dir, "index.md")

index_content = "---\n" \
                "layout: default\n" \
                "title: Home\n" \
                "toc: true\n" \
                "version: #{version}\n" \
                "---\n" \
                "#{index_src_content}"

File.write(index_dest, index_content)

puts "Created #{index_dest}..."
puts File.read(index_dest)

# Build _versions/${version}.md from current README.md
#
version_dest = File.join(root_dir, "_versions", "#{version}.md")

version_content = "---\n" \
                  "layout: version\n" \
                  "toc: true\n" \
                  "title: #{version}\n" \
                  "version: #{version}\n" \
                  "---\n" \
                  "#{index_src_content}"

File.write(version_dest, version_content)

puts "Created #{version_dest}..."
puts File.read(version_dest)

# Build licences.md from current LICENSE
#
license_src = File.join(root_dir, "LICENSE")
license_src_content = File.read(license_src)

license_dest = File.join(root_dir, "license.md")

license_content = "---\n" \
                  "layout: default\n" \
                  "toc: false\n" \
                  "title: License\n" \
                  "version: #{version}\n" \
                  "---\n" \
                  "#{license_src_content}"

File.write(license_dest, license_content)

puts "Created #{license_dest}..."
puts File.read(license_dest)

# Build versions.md from current CHANGELOG.md
#
changelog_src = File.join(root_dir, "CHANGELOG.md")
changelog_src_content = File.read(changelog_src)

changelog_src_content.gsub!(/https:\/\/github.com\/coffeebrewapps\/coffeebrew_jekyll_docs\/blob\/v/, "{{ site.baseurl }}\/versions\/")
changelog_src_content.gsub!(/\/README.md/, ".html")

changelog_dest = File.join(root_dir, "versions.md")

changelog_content = "---\n" \
                    "layout: default\n" \
                    "toc: false\n" \
                    "title: Versions\n" \
                    "version: #{version}\n" \
                    "---\n" \
                    "#{changelog_src_content}"

File.write(changelog_dest, changelog_content)

puts "Created #{changelog_dest}..."
puts File.read(changelog_dest)
