#!/bin/bash

set -e

version=$1

script/docsprep $version

###
# Build full docs/
###
JEKYLL_ENV=production bundle exec jekyll build --verbose --trace

index_dest="index.md"
license_dest="license.md"
changelog_dest="versions.md"

rm $index_dest $license_dest $changelog_dest
